// src/data.js

export const events = [
  {
    id: 1,
    title: "Investing 101",
    subtitle: "Learn the basics of investing",
    description: "An introductory workshop on investing in stocks and bonds.",
    image: {
      uri: "https://www.learn25.com/wp-content/uploads/2019/02/McGraime_G1_Coverflat-2048x2048.jpg",
    },
    startDate: "2024-07-01T10:00:00Z",
    endDate: "2024-07-01T12:00:00Z",
    location: "Conference Hall A",
    address: "123 Main St",
    city: "New York",
    state: "NY",
    country: "USA",
    latitude: 40.7128,
    longitude: -74.006,
    price: 0,
    currency: "USD",
    organizerName: "Finance Club",
    organizerContact: "contact@financeclub.com",
    category: "Workshop",
    tags: ["investing", "finance", "workshop"],
    registrationUrl: "https://example.com/register1",
    eventUrl: "https://example.com/event1",
  },
  {
    id: 2,
    title: "Budget Bootcamp",
    subtitle: "Master your finances",
    description:
      "A hands-on workshop on personal budgeting and finance management.",
    image: {
      uri: "https://tse3.mm.bing.net/th?id=OIP.tabe8MWV9PsCcnKgnGyWjAHaHa&pid=Api&P=0&h=180",
    },
    startDate: "2024-08-15T14:00:00Z",
    endDate: "2024-08-15T16:00:00Z",
    location: "Meta, Gurugram",
    address: "456 Corporate Blvd",
    city: "Gurugram",
    state: "Haryana",
    country: "India",
    latitude: 28.4595,
    longitude: 77.0266,
    price: 20,
    currency: "INR",
    organizerName: "Meta",
    organizerContact: "events@meta.com",
    category: "Seminar",
    tags: ["budgeting", "finance", "seminar"],
    registrationUrl: "https://example.com/register2",
    eventUrl: "https://example.com/event2",
  },
  {
    id: 3,
    title: "Coffee & Capital",
    subtitle: "Networking over coffee",
    description: "An opportunity to network with industry leaders over coffee.",
    image: { uri: "https://i.ytimg.com/vi/tegr2Aezpq8/maxresdefault.jpg" },
    startDate: "2024-09-10T09:00:00Z",
    endDate: "2024-09-10T11:00:00Z",
    location: "JP Morgan",
    address: "789 Finance Rd",
    city: "San Francisco",
    state: "CA",
    country: "USA",
    latitude: 37.7749,
    longitude: -122.4194,
    price: 0,
    currency: "USD",
    organizerName: "JP Morgan",
    organizerContact: "networking@jpmorgan.com",
    category: "Networking",
    tags: ["networking", "coffee", "business"],
    registrationUrl: "https://example.com/register3",
    eventUrl: "https://example.com/event3",
  },
  {
    id: 4,
    title: "Debt Destroyer",
    subtitle: "Eliminate your debt",
    description: "Strategies and tips for getting out of debt.",
    image: {
      uri: "https://tse2.mm.bing.net/th?id=OIP.V17rgMGHOjvXdVmEbFQd6QHaDt&pid=Api&P=0&h=180",
    },
    startDate: "2024-10-05T13:00:00Z",
    endDate: "2024-10-05T15:00:00Z",
    location: "Bank Chase n Co.",
    address: "101 Bank St",
    city: "Chicago",
    state: "IL",
    country: "USA",
    latitude: 41.8781,
    longitude: -87.6298,
    price: 15,
    currency: "USD",
    organizerName: "Chase Bank",
    organizerContact: "events@chase.com",
    category: "Workshop",
    tags: ["debt", "finance", "workshop"],
    registrationUrl: "https://example.com/register4",
    eventUrl: "https://example.com/event4",
  },
  {
    id: 5,
    title: "Financial Freedom",
    subtitle: "Achieve financial independence",
    description: "Steps to achieve financial independence and freedom.",
    image: {
      uri: "https://tse2.mm.bing.net/th?id=OIP.K-HLRRh6H3Lt5LHqlGIkWAHaFj&pid=Api&P=0&h=180",
    },
    startDate: "2024-11-20T10:00:00Z",
    endDate: "2024-11-20T12:00:00Z",
    location: "New York Convention Center",
    address: "200 Liberty St",
    city: "New York",
    state: "NY",
    country: "USA",
    latitude: 40.7113,
    longitude: -74.0132,
    price: 10,
    currency: "USD",
    organizerName: "Freedom Events",
    organizerContact: "info@freedomevents.com",
    category: "Conference",
    tags: ["financial freedom", "conference", "independence"],
    registrationUrl: "https://example.com/register5",
    eventUrl: "https://example.com/event5",
  },
  {
    id: 6,
    title: "Stock Market Basics",
    subtitle: "Introduction to stock trading",
    description:
      "Learn the basics of trading stocks and understanding the market.",
    image: {
      uri: "https://tse1.mm.bing.net/th?id=OIP._L_LqcVrQX89NXBtUGGSrgHaEK&pid=Api&P=0&h=180",
    },
    startDate: "2024-12-05T14:00:00Z",
    endDate: "2024-12-05T16:00:00Z",
    location: "Online Webinar",
    address: "Online",
    city: "N/A",
    state: "N/A",
    country: "N/A",
    latitude: 0,
    longitude: 0,
    price: 0,
    currency: "USD",
    organizerName: "Stock Academy",
    organizerContact: "webinar@stockacademy.com",
    category: "Webinar",
    tags: ["stocks", "trading", "webinar"],
    registrationUrl: "https://example.com/register6",
    eventUrl: "https://example.com/event6",
  },
];

// src/data.js

export const schemes = [
  {
    id: 1,
    title: "Atal Pension Yojana",
    subtitle: "Guaranteed pension for senior citizens",
    description:
      "Save small, get a guaranteed pension (Rs.1000-5000) after 60 for retirement security.",
    image: {
      uri: "https://sarkariyojnaa.org/wp-content/uploads/2023/02/atal-pension-yojna.jpg",
    },
    eligibility: "All citizens aged between 18-40 years",
    benefits: [
      "Guaranteed minimum pension of Rs.1000 to Rs.5000",
      "Secure retirement",
      "Government co-contribution for eligible subscribers",
    ],
    startDate: "2015-06-01",
    endDate: null,
    category: "Pension",
    applicationProcess: "Apply through your bank or post office",
    officialWebsite: "https://www.npscra.nsdl.co.in/nsdl/scheme-details/APY",
    contactInfo: "1800-110-069",
    documentsRequired: ["Aadhaar card", "Bank account details", "Proof of age"],
    financialSupport: "Government co-contribution for eligible subscribers",
    targetAudience: "All citizens aged between 18-40 years",
    termsAndConditions: "Subscribers must contribute until the age of 60",
    status: "Active",
  },
  {
    id: 2,
    title: "Sukanya Samriddhi Yojna",
    subtitle: "Savings plan for girl children",
    description:
      "Girl child savings plan with high interest & tax benefits. Secure her future.",
    image: {
      uri: "https://saralyojana.com/wp-content/uploads/2022/05/SSY-Sukanya-Samriddhi-Yojana-1024x576.jpg",
    },
    eligibility:
      "Parents or guardians of a girl child below the age of 10 years",
    benefits: [
      "High interest rate",
      "Tax benefits under Section 80C",
      "Secure future for the girl child",
    ],
    startDate: "2015-01-22",
    endDate: null,
    category: "Savings",
    applicationProcess: "Apply through your bank or post office",
    officialWebsite: "https://www.nsdl.co.in/ssy",
    contactInfo: "1800-222-990",
    documentsRequired: [
      "Birth certificate of the girl child",
      "Proof of identity of parents or guardians",
      "Proof of address",
    ],
    financialSupport: "High interest rate and tax benefits",
    targetAudience:
      "Parents or guardians of a girl child below the age of 10 years",
    termsAndConditions:
      "Deposits can be made for 21 years or until the girl child gets married after the age of 18",
    status: "Active",
  },
  {
    id: 3,
    title: "Public Provident Fund (PPF)",
    subtitle: "Long-term savings with guaranteed returns",
    description:
      "Low-risk, long-term savings option with guaranteed returns & tax savings.",
    image: {
      uri: "https://moneyinflow.in/wp-content/uploads/2021/07/Public-Provident-Fund-1024x493.png",
    },
    eligibility: "All Indian residents",
    benefits: [
      "Guaranteed returns",
      "Tax benefits under Section 80C",
      "Loan facility against the balance",
    ],
    startDate: "1968-01-01",
    endDate: null,
    category: "Savings",
    applicationProcess: "Apply through your bank or post office",
    officialWebsite: "https://www.nsiindia.gov.in/InternalPage.aspx?Id_Pk=82",
    contactInfo: "1800-180-1111",
    documentsRequired: [
      "Proof of identity",
      "Proof of address",
      "Passport-size photograph",
    ],
    financialSupport: "Guaranteed returns and tax benefits",
    targetAudience: "All Indian residents",
    termsAndConditions: "Lock-in period of 15 years",
    status: "Active",
  },
  {
    id: 4,
    title: "Pradhan Mantri Jan Dhan Yojna (PMJDY)",
    subtitle: "Banking for all",
    description:
      "Banking for all: PMJDY opens accounts, brings finance access.",
    image: {
      uri: "https://tse2.mm.bing.net/th?id=OIP.lah2haRMUgSuuV3l635ccgHaD4&pid=Api&P=0&h=180",
    },
    eligibility: "All Indian residents",
    benefits: [
      "Zero balance accounts",
      "Overdraft facility",
      "Accidental insurance cover",
    ],
    startDate: "2014-08-28",
    endDate: null,
    category: "Banking",
    applicationProcess: "Apply through your bank",
    officialWebsite: "https://pmjdy.gov.in/",
    contactInfo: "1800-345-6789",
    documentsRequired: [
      "Proof of identity",
      "Proof of address",
      "Passport-size photograph",
    ],
    financialSupport: "Overdraft facility and insurance cover",
    targetAudience: "All Indian residents",
    termsAndConditions: "One account per household",
    status: "Active",
  },
  // More schemes...
];

export const plans = [
  {
    id: 1,
    title: "TATA AIA Fortune Maxima",
    amountInvested: "₹25,000",
    timeInvested: "2 years",
    image: "https://via.placeholder.com/150",
    description:
      "A comprehensive retirement plan that provides life coverage and wealth creation benefits.",
    eligibility: "18 to 65 years",
    benefits: ["Wealth creation", "Life coverage", "Tax benefits"],
    category: "Wealth",
    officialWebsite: "https://www.tataaia.com",
    contactInfo: "1800-209-0101",
    documentsRequired: ["Aadhaar card", "PAN card", "Address proof"],
    financialSupport: "Guaranteed returns and bonuses",
    targetAudience: "Individuals looking for a long-term investment",
    termsAndConditions: "Policy term ranges from 10 to 40 years",
    status: "Active",
  },
  {
    id: 2,
    title: "HDFC Life Click 2 Wealth",
    amountInvested: "₹50,000",
    timeInvested: "5 years",
    image: "https://via.placeholder.com/150",
    description:
      "A unit-linked plan that offers market-linked returns along with life cover.",
    eligibility: "18 to 65 years",
    benefits: ["Market-linked returns", "Life cover", "Tax benefits"],
    category: "Wealth",
    officialWebsite: "https://www.hdfclife.com",
    contactInfo: "1800-266-9777",
    documentsRequired: ["Aadhaar card", "PAN card", "Address proof"],
    financialSupport: "Flexible premium payment options",
    targetAudience: "Individuals looking for market-linked returns",
    termsAndConditions: "Lock-in period of 5 years",
    status: "Active",
  },
  {
    id: 3,
    title: "ICICI Pru Smart Life",
    amountInvested: "₹75,000",
    timeInvested: "10 years",
    image: "https://via.placeholder.com/150",
    description:
      "A retirement plan that provides protection and savings with additional loyalty rewards.",
    eligibility: "18 to 65 years",
    benefits: ["Protection and savings", "Loyalty rewards", "Tax benefits"],
    category: "Savings",
    officialWebsite: "https://www.iciciprulife.com",
    contactInfo: "1860-266-7766",
    documentsRequired: ["Aadhaar card", "PAN card", "Address proof"],
    financialSupport: "Guaranteed loyalty additions",
    targetAudience:
      "Individuals seeking a combination of protection and savings",
    termsAndConditions: "Policy term ranges from 10 to 30 years",
    status: "Active",
  },
  {
    id: 4,
    title: "SBI Life - Retire Smart",
    amountInvested: "₹100,000",
    timeInvested: "15 years",
    image: "https://via.placeholder.com/150",
    description:
      "A non-participating unit-linked insurance plan that offers systematic retirement planning.",
    eligibility: "30 to 60 years",
    benefits: ["Systematic retirement planning", "Life cover", "Tax benefits"],
    category: "Retirement",
    officialWebsite: "https://www.sbilife.co.in",
    contactInfo: "1800-267-9090",
    documentsRequired: ["Aadhaar card", "PAN card", "Address proof"],
    financialSupport: "Regular income post retirement",
    targetAudience: "Individuals looking for a systematic retirement plan",
    termsAndConditions: "Lock-in period of 5 years",
    status: "Active",
  },
  {
    id: 5,
    title: "Max Life Forever Young Pension Plan",
    amountInvested: "₹200,000",
    timeInvested: "20 years",
    image: "https://via.placeholder.com/150",
    description:
      "A pension plan that provides regular income post-retirement with guaranteed benefits.",
    eligibility: "30 to 65 years",
    benefits: [
      "Guaranteed benefits",
      "Regular income post-retirement",
      "Tax benefits",
    ],
    category: "Pension",
    officialWebsite: "https://www.maxlifeinsurance.com",
    contactInfo: "1860-120-5577",
    documentsRequired: ["Aadhaar card", "PAN card", "Address proof"],
    financialSupport: "Guaranteed lifetime income",
    targetAudience: "Individuals planning for post-retirement income",
    termsAndConditions: "Policy term ranges from 10 to 40 years",
    status: "Active",
  },
];
